routes/web.php
<?php

use App\Http\Controllers\Auth\ApiTokenController;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Sendportal\Base\Facades\Sendportal;
use App\Http\Middleware\OwnsCurrentWorkspace;
use App\Http\Middleware\RequireWorkspace;

Auth::routes(
    [
        'verify' => config('sendportal-host.auth.register', false),
        'register' => config('sendportal-host.auth.register', false),
        'reset' => config('sendportal-host.auth.password_reset'),
    ]
);

Route::get('setup', 'SetupController@index')->name('setup');

// Auth.
Route::middleware('auth')->namespace('Auth')->group(
    static function (Router $authRouter)
    {
        // Logout.
        $authRouter->get('logout', 'LoginController@logout')->name('logout');

        // Profile.
        $authRouter->middleware('verified')->name('profile.')->prefix('profile')->group(
            static function (
                Router $profileRouter
            ) {
                $profileRouter->get('/', 'ProfileController@show')->name('show');
                $profileRouter->get('/edit', 'ProfileController@edit')->name('edit');
                $profileRouter->put('/', 'ProfileController@update')->name('update');
            }
        );

        // API Tokens.
        $authRouter->middleware('verified')->name('api-tokens.')->prefix('api-tokens')->group(static function (Router $apiTokenRouter) {
            $apiTokenRouter->get('/', [ApiTokenController::class, 'index'])->name('index');
            $apiTokenRouter->post('/', [ApiTokenController::class, 'store'])->name('store');
            $apiTokenRouter->delete('{tokenid}', [ApiTokenController::class, 'destroy'])->name('destroy');
        });
    }
);

// Workspace User Management.
Route::namespace('Workspaces')
    ->middleware(['auth', 'verified', RequireWorkspace::class, OwnsCurrentWorkspace::class])
    ->name('users.')
    ->prefix('users')
    ->group(
        static function (Router $workspacesRouter)
        {
            $workspacesRouter->get('/', 'WorkspaceUsersController@index')->name('index');
            $workspacesRouter->delete('{userId}', 'WorkspaceUsersController@destroy')->name('destroy');

            // Invitations.
            $workspacesRouter->name('invitations.')->prefix('invitations')
                ->group(
                    static function (Router $invitationsRouter)
                    {
                        $invitationsRouter->post('/', 'WorkspaceInvitationsController@store')->name('store');
                        $invitationsRouter->delete('{invitation}', 'WorkspaceInvitationsController@destroy')
                            ->name('destroy');
                    }
                );
        }
    );

// Workspace Management.
Route::namespace('Workspaces')->middleware(
    [
        'auth',
        'verified',
        RequireWorkspace::class
    ]
)->group(
    static function (Router $workspaceRouter)
    {
        $workspaceRouter->resource('workspaces', 'WorkspacesController')->except(
            [
                'create',
                'show',
                'destroy',
            ]
        );

        // Workspace Switching.
        $workspaceRouter->get('workspaces/{workspace}/switch', 'SwitchWorkspaceController@switch')
            ->name('workspaces.switch');

        // Invitations.
        $workspaceRouter->post('workspaces/invitations/{invitation}/accept', 'PendingInvitationController@accept')
            ->name('workspaces.invitations.accept');
        $workspaceRouter->post('workspaces/invitations/{invitation}/reject', 'PendingInvitationController@reject')
            ->name('workspaces.invitations.reject');
    }
);

Route::middleware(['auth', 'verified', RequireWorkspace::class])->group(
    static function ()
    {
        Sendportal::webRoutes();
    }
);

Sendportal::publicWebRoutes();

app/Models/ApiToken.php
<?php

declare(strict_types=1);

namespace App\Models;

use Carbon\Carbon;
use Database\Factories\ApiTokenFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Sendportal\Base\Models\BaseModel;

/**
 * @property int $id
 * @property string $api_token
 * @property string $description
 * @property int $workspace_id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @method static ApiTokenFactory factory
 */
class ApiToken extends BaseModel
{
    use HasFactory;

    /** @var array */
    protected $guarded = [];

    /**
     * @var array
     */
    protected $casts = [
        'workspace_id' => 'integer'
    ];

    /**
     * @param $rawHeaderValue
     * @return int|null
     */
    public static function resolveWorkspaceId($rawHeaderValue): ?int
    {
        $apiTokenInstance = self::where('api_token', $rawHeaderValue)->first();

        return $apiTokenInstance->workspace_id ?? null;
    }
}

resources/views/api-tokens/index.blade.php
@extends('sendportal::layouts.app')

@section('content')

    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card">

                <div class="card-header card-header-accent">
                    <div class="card-header-inner">
                        {{ __('API Tokens') }}
                    </div>
                </div>

                @if ($tokens->isEmpty())

                    <div class="card-body">
                        <p>No API tokens have been generated.</p>
                    </div>

                @else

                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Token</th>
                            <th>Description</th>
                            <th>Created At</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($tokens as $token)
                            <tr>
                                <td>{{ $token->api_token }}</td>
                                <td>{{ $token->description }}</td>
                                <td>{{ $token->created_at }}</td>
                                <td>
                                    <form action="{{ route('api-tokens.destroy', $token->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-xs btn-light delete-token">
                                            {{ __('Delete') }}
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                @endif

            </div>

            <div class="card mt-3">
                <div class="card-header">
                    {{ __('Add New Token') }}
                </div>
                <div class="card-body">

                    <form action="{{ route('api-tokens.store') }}" method="post">

                        @csrf
                        <div class="form-group row">
                            <label for="token-description" class="col-sm-2">{{ __('Description') }}</label>

                            <div class="col-sm-6">
                                <input type="text" id="token-description" class="form-control" name="description" placeholder="Optional description for your API token…">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="offset-sm-2 col-sm-10">
                                <input type="submit" class="btn btn-md btn-primary" value="{{ __('Add Token') }}">
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <script>
      let tokenDeleteButtons = document.getElementsByClassName('delete-token');

      Array.from(tokenDeleteButtons).forEach((element) => {
        element.addEventListener('click', (event) => {
          event.preventDefault();

          let confirmDelete = confirm('Are you sure you want to permanently delete this token?');

          if (confirmDelete) {
            element.closest('form').submit();
          }
        });
      });
    </script>

@endsection()