routes/web.php
<?php

use App\Http\Controllers\Auth\ApiTokenController;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Sendportal\Base\Facades\Sendportal;
use App\Http\Middleware\OwnsCurrentWorkspace;
use App\Http\Middleware\RequireWorkspace;

Auth::routes(
    [
        'verify' => config('sendportal-host.auth.register', false),
        'register' => config('sendportal-host.auth.register', false),
        'reset' => config('sendportal-host.auth.password_reset'),
    ]
);

Route::get('setup', 'SetupController@index')->name('setup');

// Auth.
Route::middleware('auth')->namespace('Auth')->group(
    static function (Router $authRouter)
    {
        // Logout.
        $authRouter->get('logout', 'LoginController@logout')->name('logout');

        // Profile.
        $authRouter->middleware('verified')->name('profile.')->prefix('profile')->group(
            static function (
                Router $profileRouter
            ) {
                $profileRouter->get('/', 'ProfileController@show')->name('show');
                $profileRouter->get('/edit', 'ProfileController@edit')->name('edit');
                $profileRouter->put('/', 'ProfileController@update')->name('update');
            }
        );

        // API Tokens.
        $authRouter->middleware('verified')->name('api-tokens.')->prefix('api-tokens')->group(static function (Router $apiTokenRouter) {
            $apiTokenRouter->get('/', [ApiTokenController::class, 'index'])->name('index');
            $apiTokenRouter->post('/', [ApiTokenController::class, 'store'])->name('store');
            $apiTokenRouter->delete('{tokenid}', [ApiTokenController::class, 'destroy'])->name('destroy');
        });
    }
);

// Workspace User Management.
Route::namespace('Workspaces')
    ->middleware(['auth', 'verified', RequireWorkspace::class, OwnsCurrentWorkspace::class])
    ->name('users.')
    ->prefix('users')
    ->group(
        static function (Router $workspacesRouter)
        {
            $workspacesRouter->get('/', 'WorkspaceUsersController@index')->name('index');
            $workspacesRouter->delete('{userId}', 'WorkspaceUsersController@destroy')->name('destroy');

            // Invitations.
            $workspacesRouter->name('invitations.')->prefix('invitations')
                ->group(
                    static function (Router $invitationsRouter)
                    {
                        $invitationsRouter->post('/', 'WorkspaceInvitationsController@store')->name('store');
                        $invitationsRouter->delete('{invitation}', 'WorkspaceInvitationsController@destroy')
                            ->name('destroy');
                    }
                );
        }
    );

// Workspace Management.
Route::namespace('Workspaces')->middleware(
    [
        'auth',
        'verified',
        RequireWorkspace::class
    ]
)->group(
    static function (Router $workspaceRouter)
    {
        $workspaceRouter->resource('workspaces', 'WorkspacesController')->except(
            [
                'create',
                'show',
                'destroy',
            ]
        );

        // Workspace Switching.
        $workspaceRouter->get('workspaces/{workspace}/switch', 'SwitchWorkspaceController@switch')
            ->name('workspaces.switch');

        // Invitations.
        $workspaceRouter->post('workspaces/invitations/{invitation}/accept', 'PendingInvitationController@accept')
            ->name('workspaces.invitations.accept');
        $workspaceRouter->post('workspaces/invitations/{invitation}/reject', 'PendingInvitationController@reject')
            ->name('workspaces.invitations.reject');
    }
);

Route::middleware(['auth', 'verified', RequireWorkspace::class])->group(
    static function ()
    {
        Sendportal::webRoutes();
    }
);

Sendportal::publicWebRoutes();

resources/views/layouts/header/userManagementHeader.blade.php
@auth()
    <ul class="navbar-nav flex-row ml-md-auto d-md-flex">
        @php $workspaces = auth()->user()->workspaces @endphp

        @if (count($workspaces) == 1)
            <li class="nav-item mr-5 px-2">
            <span class="nav-link" id="bd-versions" aria-haspopup="true" aria-expanded="false">
                 {{ auth()->user()->currentWorkspace->name }}
            </span>
            </li>
        @elseif (count($workspaces) > 1 && auth()->user()->currentWorkspace)
            <li class="nav-item dropdown mr-4 px-2 workspace-select">
                <a class="nav-link dropdown-toggle color-purple-500" href="#" id="bd-versions"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {{ auth()->user()->currentWorkspace->name }}<i class="ml-2 fas fa-caret-down color-gray-500"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
                    @foreach($workspaces as $workspace)
                        <a class="dropdown-item px-3" href="{{ route('workspaces.switch', $workspace->id) }}">
                            <i class="fas fa-circle mr-2 {{ auth()->user()->currentWorkspace->id == $workspace->id ? 'color-purple-500' : 'color-gray-300' }}"></i>{{ $workspace->name }}
                        </a>
                    @endforeach
                </div>
            </li>
        @endif

        <li class="nav-item dropdown pl-3 user-dropdown">

            <a class="nav-link dropdown-toggle mr-md-1 color-purple-500" href="#" id="bd-versions"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
               title="{{{ auth()->user()->full_name }}}">
                <img src="{{{ auth()->user()->avatar }}}" height="25" class="rounded-circle mr-2"
                     alt="{{ auth()->user()->name }}">
                <span class="d-none d-sm-inline-block">{{{ \Illuminate\Support\Str::limit( auth()->user()->name, 25) }}}</span>
                <i
                        class="ml-2 fas fa-caret-down color-gray-500"></i>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">

                {{-- My Profile --}}
                <a class="dropdown-item px-3" href="{{ route('profile.show') }}"><i
                            class="fas fa-user mr-2 color-gray-300"></i>{{ __('My Profile') }}</a>

                {{-- Workspaces --}}
                <a class="dropdown-item px-3" href="{{ route('workspaces.index') }}"><i
                            class="fas fa-layer-group mr-2 color-gray-300"></i>{{ __('Workspaces') }}</a>

                {{-- API Tokens --}}
                <a class="dropdown-item px-3" href="{{ route('api-tokens.index') }}"><i
                            class="fas fa-layer-group mr-2 color-gray-300"></i>{{ __('API Tokens') }}</a>

                <div class="dropdown-divider"></div>
                <a class="dropdown-item px-3" href="{{ route('logout') }}"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i
                            class="fas fa-sign-out-alt mr-2 color-gray-300"></i>Log out</a>
            </div>
        </li>
    </ul>

    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
    </form>
@endauth