routes/web.php
<?php

use App\Http\Controllers\Auth\ApiTokenController;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Sendportal\Base\Facades\Sendportal;
use App\Http\Middleware\OwnsCurrentWorkspace;
use App\Http\Middleware\RequireWorkspace;

Auth::routes(
    [
        'verify' => config('sendportal-host.auth.register', false),
        'register' => config('sendportal-host.auth.register', false),
        'reset' => config('sendportal-host.auth.password_reset'),
    ]
);

Route::get('setup', 'SetupController@index')->name('setup');

// Auth.
Route::middleware('auth')->namespace('Auth')->group(
    static function (Router $authRouter)
    {
        // Logout.
        $authRouter->get('logout', 'LoginController@logout')->name('logout');

        // Profile.
        $authRouter->middleware('verified')->name('profile.')->prefix('profile')->group(
            static function (
                Router $profileRouter
            ) {
                $profileRouter->get('/', 'ProfileController@show')->name('show');
                $profileRouter->get('/edit', 'ProfileController@edit')->name('edit');
                $profileRouter->put('/', 'ProfileController@update')->name('update');
            }
        );

        // API Tokens.
        $authRouter->middleware('verified')->name('api-tokens.')->prefix('api-tokens')->group(static function (Router $apiTokenRouter) {
            $apiTokenRouter->get('/', [ApiTokenController::class, 'index'])->name('index');
            $apiTokenRouter->post('/', [ApiTokenController::class, 'store'])->name('store');
            $apiTokenRouter->delete('{tokenid}', [ApiTokenController::class, 'destroy'])->name('destroy');
        });
    }
);

// Workspace User Management.
Route::namespace('Workspaces')
    ->middleware(['auth', 'verified', RequireWorkspace::class, OwnsCurrentWorkspace::class])
    ->name('users.')
    ->prefix('users')
    ->group(
        static function (Router $workspacesRouter)
        {
            $workspacesRouter->get('/', 'WorkspaceUsersController@index')->name('index');
            $workspacesRouter->delete('{userId}', 'WorkspaceUsersController@destroy')->name('destroy');

            // Invitations.
            $workspacesRouter->name('invitations.')->prefix('invitations')
                ->group(
                    static function (Router $invitationsRouter)
                    {
                        $invitationsRouter->post('/', 'WorkspaceInvitationsController@store')->name('store');
                        $invitationsRouter->delete('{invitation}', 'WorkspaceInvitationsController@destroy')
                            ->name('destroy');
                    }
                );
        }
    );

// Workspace Management.
Route::namespace('Workspaces')->middleware(
    [
        'auth',
        'verified',
        RequireWorkspace::class
    ]
)->group(
    static function (Router $workspaceRouter)
    {
        $workspaceRouter->resource('workspaces', 'WorkspacesController')->except(
            [
                'create',
                'show',
                'destroy',
            ]
        );

        // Workspace Switching.
        $workspaceRouter->get('workspaces/{workspace}/switch', 'SwitchWorkspaceController@switch')
            ->name('workspaces.switch');

        // Invitations.
        $workspaceRouter->post('workspaces/invitations/{invitation}/accept', 'PendingInvitationController@accept')
            ->name('workspaces.invitations.accept');
        $workspaceRouter->post('workspaces/invitations/{invitation}/reject', 'PendingInvitationController@reject')
            ->name('workspaces.invitations.reject');
    }
);

Route::middleware(['auth', 'verified', RequireWorkspace::class])->group(
    static function ()
    {
        Sendportal::webRoutes();
    }
);

Sendportal::publicWebRoutes();

app/Models/Workspace.php
<?php

declare(strict_types=1);

namespace App\Models;

use Carbon\Carbon;
use Database\Factories\WorkspaceFactory;
use Exception;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Sendportal\Base\Models\BaseModel;

/**
 * @property int $id
 * @property int $owner_id
 * @property string $name
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @property User $owner
 * @property EloquentCollection $users
 * @property EloquentCollection $invitations
 *
 * @method static WorkspaceFactory factory
 */
class Workspace extends BaseModel
{
    use HasFactory;

    public const ROLE_OWNER = 'owner';
    public const ROLE_MEMBER = 'member';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'owner_id',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'card_brand',
        'card_last_four',
        'card_country',
        'billing_address',
        'billing_address_line_2',
        'billing_city',
        'billing_state',
        'billing_zip',
        'billing_country',
        'extra_billing_information',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'owner_id' => 'int',
        'trial_ends_at' => 'datetime',
    ];

    /**
     * Get the owner of the workspace.
     */
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class, 'owner_id');
    }

    /**
     * Get all of the users that belong to the workspace.
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'workspace_users')
            ->orderBy('name')
            ->withPivot('role')
            ->withTimestamps();
    }

    /**
     * Get all of the workspace's invitations.
     */
    public function invitations(): HasMany
    {
        return $this->hasMany(Invitation::class);
    }

    /**
     * Detach all of the users from the workspace and delete the workspace.
     *
     * @return void
     * @throws Exception
     */
    public function detachUsersAndDestroy(): void
    {
        $this->users()
            ->where('current_workspace_id', $this->id)
            ->update(['current_workspace_id' => null]);

        $this->users()->detach();

        $this->delete();
    }
}

app/Http/Controllers/Workspaces/PendingInvitationController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Workspaces;

use App\Http\Controllers\Controller;
use App\Models\Invitation;
use App\Services\Workspaces\AcceptInvitation;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PendingInvitationController extends Controller
{
    /** @var AcceptInvitation */
    protected $acceptInvitation;

    public function __construct(AcceptInvitation $acceptInvitation)
    {
        $this->acceptInvitation = $acceptInvitation;
    }

    /**
     * @throws Exception
     */
    public function accept(Request $request, Invitation $invitation): RedirectResponse
    {
        abort_unless($request->user()->id === $invitation->user_id, 404);

        if ($invitation->isExpired()) {
            return redirect()->back()->with('error', __('The invitation is no longer valid.'));
        }

        $this->acceptInvitation->handle($request->user(), $invitation);

        return redirect()->route('workspaces.index');
    }

    /**
     * @throws Exception
     */
    public function reject(Request $request, Invitation $invitation): RedirectResponse
    {
        abort_unless($request->user()->id === $invitation->user_id, 404);

        $invitation->delete();

        return redirect()->route('workspaces.index');
    }
}

app/Http/Controllers/Workspaces/SwitchWorkspaceController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Workspaces;

use Illuminate\Http\Request;
use App\Models\Workspace;
use Illuminate\Http\RedirectResponse;

class SwitchWorkspaceController
{
    public function switch(Request $request, Workspace $workspace): RedirectResponse
    {
        $user = $request->user();

        abort_unless($user->onWorkspace($workspace), 404);

        $user->switchToWorkspace($workspace);

        return redirect()->route('sendportal.dashboard');
    }
}

app/Http/Controllers/Workspaces/WorkspaceInvitationsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Workspaces;

use Exception;
use Illuminate\Http\RedirectResponse;
use App\Http\Controllers\Controller;
use App\Http\Middleware\OwnsCurrentWorkspace;
use App\Http\Requests\Workspaces\WorkspaceInvitationStoreRequest;
use App\Models\Invitation;
use App\Services\Workspaces\SendInvitation;

class WorkspaceInvitationsController extends Controller
{
    /** @var SendInvitation */
    protected $sendInvitation;

    public function __construct(SendInvitation $sendInvitation)
    {
        $this->sendInvitation = $sendInvitation;

        $this->middleware(OwnsCurrentWorkspace::class)->only(['store']);
    }

    /**
     * @throws Exception
     */
    public function store(WorkspaceInvitationStoreRequest $request): RedirectResponse
    {
        $workspace = $request->user()->currentWorkspace();

        $this->sendInvitation->handle($workspace, $request->email);

        return redirect()->route('users.index');
    }

    /**
     * @throws Exception
     */
    public function destroy(Invitation $invitation): RedirectResponse
    {
        $invitation->delete();

        return redirect()->route('users.index');
    }
}

app/Http/Controllers/Workspaces/WorkspaceUsersController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Workspaces;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View as ViewContract;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Models\User;
use App\Services\Workspaces\RemoveUserFromWorkspace;

class WorkspaceUsersController extends Controller
{
    /** @var RemoveUserFromWorkspace */
    private $removeUserFromWorkspace;

    public function __construct(RemoveUserFromWorkspace $removeUserFromWorkspace)
    {
        $this->removeUserFromWorkspace = $removeUserFromWorkspace;
    }

    public function index(Request $request): ViewContract
    {
        return view('users.index', [
            'users' => $request->user()->currentWorkspace->users,
            'invitations' => $request->user()->currentWorkspace->invitations,
        ]);
    }

    /**
     * Remove a user from the current workspace.
     *
     * @param int $userId
     *
     * @return RedirectResponse
     */
    public function destroy(Request $request, int $userId): RedirectResponse
    {
        /* @var $requestUser \App\Models\User */
        $requestUser = $request->user();

        if ($userId === $requestUser->id) {
            return redirect()
                ->back()
                ->with('error', __('You cannot remove yourself from your own workspace.'));
        }

        $workspace = $requestUser->currentWorkspace();

        $user = User::find($userId);

        $this->removeUserFromWorkspace->handle($user, $workspace);

        return redirect()
            ->route('users.index')
            ->with(
                'success',
                __(':user was removed from :workspace.', ['user' => $user->name, 'workspace' => $workspace->name])
            );
    }
}

app/Http/Controllers/Workspaces/WorkspacesController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Workspaces;

use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Contracts\View\View as ViewContract;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Middleware\OwnsRequestedWorkspace;
use App\Http\Requests\Workspaces\WorkspaceStoreRequest;
use App\Http\Requests\Workspaces\WorkspaceUpdateRequest;
use App\Models\Workspace;
use App\Repositories\WorkspacesRepository;
use App\Services\Workspaces\CreateWorkspace;

class WorkspacesController extends Controller
{
    /** @var WorkspacesRepository */
    protected $workspaces;

    /** @var CreateWorkspace */
    protected $createWorkspace;

    public function __construct(WorkspacesRepository $workspaces, CreateWorkspace $createWorkspace)
    {
        $this->workspaces = $workspaces;
        $this->createWorkspace = $createWorkspace;

        $this->middleware(OwnsRequestedWorkspace::class)->only([
            'edit',
            'update'
        ]);
    }

    public function index(Request $request): ViewContract
    {
        $user = $request->user()->load('workspaces', 'invitations.workspace');

        return view('workspaces.index', [
            'workspaces' => $user->workspaces,
            'invitations' => $user->invitations,
        ]);
    }

    /**
     * @throws Exception
     */
    public function store(WorkspaceStoreRequest $request): RedirectResponse
    {
        $this->createWorkspace->handle($request->user(), $request->get('name'), Workspace::ROLE_OWNER);

        return redirect()->route('workspaces.index');
    }

    public function edit(Workspace $workspace): ViewContract
    {
        return view('workspaces.edit', [
            'workspace' => $workspace
        ]);
    }

    /**
     * @throws Exception
     */
    public function update(WorkspaceUpdateRequest $request, Workspace $workspace): RedirectResponse
    {
        $this->workspaces->update($workspace->id, ['name' => $request->get('workspace_name')]);

        return redirect()->route('workspaces.index');
    }
}

resources/views/workspaces/edit.blade.php
@extends('sendportal::layouts.app')

@section('heading', __('Edit Workspace'))

@section('content')
    <div class="row">
        <div class="col-lg-8 offset-lg-2">

            <div class="card">
                <div class="card-header">
                    {{ __('Update Workspace Name') }}
                </div>

                <div class="card-body">
                    <form action="{{ route('workspaces.update', $workspace) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="workspace_name"
                                   class="col-md-2 col-form-label">{{ __('Workspace Name') }}</label>

                            <div class="col-md-6">
                                <input type="text" id="edit-workspace-name" class="form-control" name="workspace_name"
                                       value="{{ $workspace->name }}">
                            </div>
                        </div>

                        <input type="submit" class="btn btn-sm btn-primary" value="{{ __('Save') }}">
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/workspaces/index.blade.php
@extends('sendportal::layouts.app')

@section('heading')
    {{ __('Workspaces') }}
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-8 offset-lg-2">

            <div class="card">
                <div class="card-header">
                    {{ __('Current Workspaces') }}
                </div>
                <div class="card-table">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>
                                <div class="pl-2">
                                    {{ __('Name') }}
                                </div>
                            </th>
                            <th width="30%">{{ __('Owner') }}</th>
                            <th width="10%">&nbsp;</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach ($workspaces as $workspace)
                            <tr>
                                <td>
                                    <div class="pl-2">
                                        {{ $workspace->name }}
                                    </div>
                                </td>
                                <td>
                                    @if (auth()->user()->id === $workspace->owner_id)
                                        You
                                    @else
                                        {{ $workspace->owner->name }}
                                    @endif
                                </td>
                                <td class="td-fit">
                                    @if (auth()->user()->ownsWorkspace($workspace))
                                        <a href="{{route('workspaces.edit', $workspace->id)}}" class="btn btn-light btn-sm">{{ __('Edit') }}</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            @if (count($invitations))
                <div class="card mt-3">
                    <div class="card-header">
                        <div class="card-header-inner">
                            {{ __('Invitations') }}
                        </div>
                    </div>

                    <div class="card-table">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>{{ __('Workspace') }}</th>
                                <th width="15%">{{ __('Invited') }}</th>
                                <th width="15%">{{ __('Expires') }}</th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach ($invitations as $invitation)
                                <tr>
                                    <td>{{ $invitation->workspace->name }}</td>
                                    <td>{{ $invitation->created_at->format('Y-m-d') }}</td>
                                    <td>
                                        <span class="{{ $invitation->isExpired() ? 'text-danger' : null }}">
                                            {{ $invitation->expires_at->format('Y-m-d') }}
                                        </span>
                                    </td>
                                    <td class="td-fit">
                                        {{-- Accept --}}
                                        <form action="{{ route('workspaces.invitations.accept', $invitation) }}"
                                              method="post" style="display:inline-block;">
                                            @csrf
                                            <input
                                                type="submit"
                                                value="{{ __('Accept') }}"
                                                class="btn btn-sm btn-light"
                                                @if ($invitation->isExpired())
                                                disabled
                                                title="{{ __('This invitation has expired.') }}"
                                                @endif
                                            >
                                        </form>
                                        {{-- Reject --}}
                                        <form action="{{ route('workspaces.invitations.reject', $invitation) }}"
                                              method="post" style="display:inline-block;">
                                            @csrf
                                            <input type="submit" value="{{ __('Reject') }}"
                                                   class="btn btn-sm btn-light">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @endif

            <div class="card mt-3">
                <div class="card-header">
                    <div class="card-header-inner">
                        {{ __('Add Workspace') }}
                    </div>
                </div>
                <div class="card-body">

                    <form action="{{ route('workspaces.store') }}" method="post">
                        @csrf
                        <div class="form-group row">
                            <label for="create-workspace-name"
                                   class="col-md-2 col-form-label">{{ __('Workspace Name') }}</label>

                            <div class="col-md-6">
                                <input type="text" id="create-workspace-name" class="form-control" name="name">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-2">
                                <input type="submit" class="btn btn-md btn-primary" value="{{ __('Save') }}">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection